### ISSUE TITLE
npm does not run using sudo

### ISSUE THREAD

**Issue by jorgebo10** [willdurand/puppet-nodejs#100]
hi guys, i'm having the following error and don't know how to fix it.

site.pp

{code}
node 'develop' {
	class { 'nodejs':
		version => 'stable',
	}

	package {'yo':
		provider => 'npm',
		ensure   => 'present',
		require => Class["nodejs"],
	}
	
	 package { 'grunt-cli':
		provider => 'npm',
		ensure   => 'present',
		require => Class["nodejs"],
    }
	
    package { 'bower':
		provider => 'npm',
		ensure   => 'present',
		require => Class["nodejs"],
    }
}

{/code}

{code}
==> default: err: /Stage[main]//Node[develop]/Package[yo]/ensure: change from ab
sent to present failed: Execution of '/usr/local/node/node-default/bin/npm insta
ll --global yo' returned 1:
==> default: > spawn-sync@1.0.13 postinstall /usr/local/node/node-v0.12.7/lib/no
de_modules/yo/node_modules/cross-spawn/node_modules/spawn-sync
==> default: > node postinstall
==> default:
==> default: sh: 1: node: not found
==> default: npm ERR! Linux 3.2.0-23-generic-pae
==> default: npm ERR! argv "/usr/local/node/node-v0.12.7/bin/node" "/usr/local/n
ode/node-default/bin/npm" "install" "--global" "yo"
==> default: npm ERR! node v0.12.7
==> default: npm ERR! npm  v2.11.3
==> default: npm ERR! file sh
==> default: npm ERR! code ELIFECYCLE
==> default: npm ERR! errno ENOENT
==> default: npm ERR! syscall spawn
==> default:
==> default: npm ERR! spawn-sync@1.0.13 postinstall: `node postinstall`
==> default: npm ERR! spawn ENOENT
==> default: npm ERR!
==> default: npm ERR! Failed at the spawn-sync@1.0.13 postinstall script 'node p
ostinstall'.
==> default: npm ERR! This is most likely a problem with the spawn-sync package,

==> default: npm ERR! not with npm itself.
==> default: npm ERR! Tell the author that this fails on your system:
==> default: npm ERR!     node postinstall
==> default: npm ERR! You can get their info via:
==> default: npm ERR!     npm owner ls spawn-sync
==> default: npm ERR! There is likely additional logging output above.
==> default:
==> default: npm ERR! Please include the following file with any support request
:
==> default: npm ERR!     /home/vagrant/npm-debug.log
==> default:
==> default: notice: /Stage[main]//Node[develop]/Package[grunt-cli]/ensure: crea
ted
{/code}

Any idea why npm does not run as sudo?
Thanks,

**Comment by vrtxf** [comment]
As suggested in the documentation the bin folder is in a path that on most systems does not reside inside the "secure" paths listed inside /etc/sudoers file on your target environment. Due to the behaviour of that file the sudo command does not carry over the environment variables that you need to run node/npm - a "which node" or npm will give you the location of those executables and you can "cat /etc/sudoers" to see the secure path dissonance. The simplest fix that you can apply is to include an alias like sudo='/usr/bin/sudo -i' or just run your sudo commands with the -i flag as that will keep your environment variables from the user you are running sudo.
There are of course multiple fixes ranging from simple to very complicated based on linux knowledge, the most elegant to my understanding being adding the proper node path to your /etc/sudoers file. I moved away towards the puppet/nodejs package as that one fit my configuration needs more. 
Hope this helps someone willing to fix this plugin !

**Comment by Wuntenn** [comment]
I had the same issue. If you run "sudo visudo" and check the secure paths also. It's as vrtxt said, when you run sudo I uses a different set of paths to resolve there whereabouts of the commands. The location where node is installed is not within any of those locations.

        file { 'create-node-symlink':
                ensure          => link,
                require         => Class['nodejs'],
                target          => '/usr/local/node/node-default/bin/node',
                path            => '/usr/local/bin/node' 
        }   
        file { 'create-npm-symlink':
                ensure          => link,
                require         => Class['nodejs'],
                target          => '/usr/local/node/node-default/bin/npm',
                path            => '/usr/local/bin/npm' 
        }  

I got around this issue by creating a symlink within the secure directory that points to node and another that points to npm.

This appears to fix things, however only in the short-term! Simple files can be installed, however other stuff that rely on node-gyp raise another error:

gyp WARN EACCES user "undefined" does not have permission to access the dev dir "/root/.node-gyp/5.0.0"

From what I've read these are related to the npm prefix. The prefix tells npm where to install and look for globally installed packages (you want this to be in a globally accessible location). You can find out what it is by running: npm config get prefix (see here: https://docs.npmjs.com/getting-started/fixing-npm-permissions).

The problem here seems to be that Puppet use the root user to install everything. Somehow npm install seems to end up in the /root/ folder even after changing the prefix. If I hadn't had so many issues with puppetlabs-nodejs I'd also be considering switching over...

**Comment by Wuntenn** [comment]
I forgot to mention I after adding the symlinks you'll get errors regarding ownership of nodes default directory (root owns it). I fixed this with:

        file { '/usr/local/node/node-default/bin':
                ensure          => 'directory',
                group           => 'wheel',
                owner           => 'meeeee',
                recurse         => true,    
                require         => Class['nodejs'],
        } 

Where meeeeeeeee is youuuuu! :D

**Comment by Ma27** [comment]
the "node" executable can't be found by puppet. Should be the same issue as in #108
