### ISSUE TITLE
Improve regex to support "hardwaremodel" = "armv7l"

### ISSUE THREAD

**Issue by gesinn-it** [willdurand/puppet-nodejs#145]
I'd like install node from the binaries distribution on a Raspberry Pi 3 with Raspian which has "hardwaremodel" = "armv7l".

I tried to add "armv7l" as option to the $node_arch selector in manifests/install.pp but this seems to be not sufficient. It still defaults to "x86". I'm sure I have overlooked something.

Any hints?

**Comment by Ma27** [comment]
ok I've just had a look at the code and no, you didn't overlook something, there's unfortunately no support for a lot of hardware :/

I'm aware of this - the installer is lacking a lot of stuff (you've just observed another case which is not supported), but it still supports old stuff like Node 0.6

Due to this increasing amount of issues I'm experiencing, I've decided to do a 2.0 where large parts of the implementation will be refactored.

**Comment by Ma27** [comment]
see #150

**Comment by Ma27** [comment]
scheduled for 2.0.0
